### ISSUE TITLE
Add FaaS template based on RestRserve

### ISSUE THREAD

**Issue by mrchypark** [analythium/openfaas-rstats-templates#14]
I hope to add template using [RestRserve](https://github.com/rexyai/RestRserve) package for template.

**Comment by psolymos** [comment]
@mrchypark {RestRserve} looks like a really nice project that does not rely on {httpuv} (unlike {opencpu} and {plumber} etc), so I am definitely interested. I'll look into it more. I would call the template `rstats-restr`

**Comment by mrchypark** [comment]
cool 

template name is rstats-restr is better.
I already try this, but it's not work for me. 

https://github.com/mrchypark/openfaas-rstats-templates/tree/master/template/rstats-rest

**Comment by psolymos** [comment]
These Dockerfiles might give us hints: https://github.com/rexyai/RestRserve/tree/master/docker

**Comment by psolymos** [comment]
The Dockerfile describes the general workflow. Main learnings:

1. RestRserve app works locally via `Rscript index.R` and curl
2. Works locally from Dockerfile without of-watchdog
3. RestRserve + of-watchdog is throwing JSON parsing error (but service is running and handling requests)
4. Workload is not ready when deployed to OpenFaaS cluster (Dockerfile, no of-watchdog, port 8080 + healthcheck)

Avenues:

- Ideally we want to understand why of-watchdog is not working properly with RestRserve (might be an Rserve level issue)
- Deploying as workload without of-watchdog should work, but it is less ideal.

See branch [restrserve-base](https://github.com/analythium/openfaas-rstats-templates/compare/restrserve-base)

**Comment by psolymos** [comment]
Closing this for now. Could this not be working due to of not supporting web sockets? RestRServe, OpenCPU, Shiny, all work without the watchdog layer, which got me wondering along this open issue: https://github.com/openfaas/of-watchdog/issues/20
